library(ggplot2)
library(reshape2)
library(plyr)
library(dplyr)
library(readxl)
library(stringr)
library(padr)
library(tidyr)
library(gridExtra)
library(scales)
library(tidyverse)

lappend <- function(lst, obj) {
  lst[[length(lst)+1]] <- obj
  return(lst)
}

reverselog_trans <- function(base = exp(1)) {
  trans <- function(x) -log(x, base)
  inv <- function(x) base^(-x)
  trans_new(paste0("reverselog-", format(base)), trans, inv, 
            log_breaks(base = base), 
            domain = c(1e-100, Inf))
}

# basedir <- "/Users/ldmonroe/Desktop/"
basedir <- "Z:/paguirigan_a/user/lmonroe/XNA_Diacarta/"
allresults <- list.files(paste0(basedir, "Results/"), pattern = ".csv")

setwd(paste0(basedir, "Results PPT/"))
mixkv <- data.frame(read_xlsx("Mix_Key-Value.xlsx"), stringsAsFactors = F)
setwd(paste0(basedir, "Results/"))

# Certain earlier runs were used, so pull those from mixkv
earlyruns <- allresults[substr(allresults, 0, 8) %in% mixkv$Date]

# longerAnneal was the first one to use the final run parameters.
lateruns <- allresults[c(grep("longerAnneal", allresults):length(allresults))]

# Rather than messily hash out start/end of dates, just take overlarge earlyruns
#   and find union with allresults
allresults <- unique(c(earlyruns, lateruns))

  # Make into a dataframe for better purging
descriptions <- substring(allresults, regexpr("_", allresults)+1)
descriptions <- substr(descriptions,
                       regexpr("-", descriptions)+1,
                       regexpr(".csv", descriptions)-1)
dates <- substr(allresults, 0, regexpr("_", allresults)-1)
allresults <- data.frame(allresults, dates, descriptions, stringsAsFactors = F)

  # Generated by other crunch scripts
allresults <- allresults %>% filter(!str_detect(descriptions, "output"))
  # If it needed cleaning, keep those.
      #Checks if name + "Cleaned" is present and omits those.  New syntax!
allresults <- allresults %>%
                filter(!(paste0(descriptions, "_Cleaned") %in% descriptions))
colnames(allresults) <- c("Filename", "Date", "Description")

rm(dates, descriptions)

setwd(paste0(basedir, "Results/"))

# Files have been selected.  Next up, read in and harmonize
columns <- list()

# Clean up inconsistencies and bind files into a list as data frames
columns <- lapply(allresults$Filename, function(x) {
  df <- data.frame(read.csv(file = x, stringsAsFactors = F), stringsAsFactors = F)
  if("End.RFU" %in% colnames(df)) {
    df <- df %>% select(-End.RFU)
  }
  if(!("Template" %in% colnames(df))) {
    df$Template <- 13
  }
  if(!("Fluor" %in% colnames(df))) { # Only applies to plasmid runs
    ifelse(!("Target" %in% colnames(df)),
           df$Fluor <- "FAM",
           df$Fluor <- df$Target)
  }
  if("Fluor" %in% colnames(df) && "Target" %in% colnames(df)) {
    df <- df %>% select(-Target)
  }
  df <- df[c("Well", "Fluor", "Sample", "Cq", "Template")]
  
  df <- df %>% mutate(Fluor = ifelse(Fluor == "Cal Orange 560", "HEX", Fluor))
  columns <- lappend(columns, df)
})

# Added an extra level somehow
columns <- unlist(columns, recursive = F)
names(columns) <- allresults$Date
combdf <- do.call(rbind, columns)

# Differentiate runs
combdf$Date <- rownames(combdf)
combdf <- combdf %>% mutate(Date = str_extract(Date, "^[0-9]*"))

# Row for mix, Col for pairing
combdf <- join(combdf, select(allresults, c(Date, Description)), by = "Date")
combdf <- combdf %>% mutate(Row = str_extract(Well, "^[A-Z]"),
                          Col = str_extract(Well, "[0-9]*$")) %>% select(-Well)

# Fix e11/e8 carryover from glomming
combdf$Fluor <- gsub("e11", "FAM", combdf$Fluor)
combdf$Fluor <- gsub("e8", "HEX", combdf$Fluor)

# "Row" is only helpful for matching to "Mix".  "Column" TBD
combdf <- join(combdf, mixkv, by = c("Date", "Row"))

combdf$Cq[which(combdf$Cq == "NaN")] <- NA

# Next up: aggregation.  Remove NAs, I guess...?

# Needs to happen after Mix
meandf <- combdf %>% group_by(Fluor, Sample, Date, XNA, Description, Template) %>%
  summarise(Cq = round(mean(Cq, na.rm = T), digits = 2))

# Get rid of this for now, can remove this step later
meandf <- meandf %>% select(-Template)

# Start to harmonize "Sample".  Oof.
  # Caps, spaces
meandf$Sample <- gsub("1E", "1e", meandf$Sample)
meandf$Sample <- gsub(" DNA", "", meandf$Sample)
meandf$Sample <- gsub(" ng", "ng", meandf$Sample)
meandf$Sample <- gsub(" pg", "pg", meandf$Sample)
meandf$Sample <- gsub("0.01ng", "10pg", meandf$Sample)
meandf$Sample <- gsub("0.1ng", "100pg", meandf$Sample)
meandf$Sample <- gsub("IN", "in", meandf$Sample)
meandf$Sample <- gsub("mut", "MUT", meandf$Sample)
meandf$Sample <- gsub("Mol$", "Molm", meandf$Sample)
meandf$Sample <- gsub("MOLM", "Molm", meandf$Sample)
meandf$Sample <- gsub("OCI Tit", "OCI in Molm Tit", meandf$Sample)
meandf$Sample <- gsub("OCI in MOL$", "OCI in Molm", meandf$Sample)

  # Inconsistent naming
meandf$Sample <- gsub("Tit ", "", meandf$Sample)

  # Create another titration column to keep reps separate but allow similar plotting
meandf <- meandf %>% mutate(Rep = ifelse(str_detect(Sample, "OCI [A-Z]{1}$"),
                                       str_extract(Sample, "[A-Z]{1}$"), NA))

meandf$Sample <- gsub(" OCI [A-Z]{1}$", " OCI", meandf$Sample)
meandf$Sample <- gsub(" Molm [A-Z]{1}$", " Molm", meandf$Sample)
meandf$Sample <- gsub("% OCI in Molm", " OCI in Molm", meandf$Sample)
meandf$Sample <- gsub("^[.]", "0.", meandf$Sample)
meandf$Sample <- gsub("% OCI$", " OCI in Molm", meandf$Sample)
meandf$XNA <- gsub("0$", "0uM", meandf$XNA)
meandf$Sample <- gsub("Molm 100", "100ng Molm", meandf$Sample)
meandf$Sample <- gsub("Molm-L1", "Molm", meandf$Sample)
meandf$Sample <- gsub("OCI 100", "100ng OCI", meandf$Sample)
meandf$Sample <- gsub("H20", "H2O", meandf$Sample)
meandf$Sample <- gsub("^OCI$", "100ng OCI", meandf$Sample)
meandf$Sample <- gsub("^Molm$", "100ng Molm", meandf$Sample)

meandf <- meandf %>% ungroup(XNA) %>%
  mutate(XNA = replace_na(XNA, "0.5uM"))
  
  # Plasmid, DNA, Stock, NTC
meandf <- meandf %>% mutate(RefMat = ifelse(str_detect(Sample, "e"), "Plasmid", "DNA"),
                            # RefMat = ifelse(str_detect(Sample, "100ng") || str_detect(Sample, "2e7"),
                            #                 "Both", RefMat),
                            RefMat = ifelse(Sample == "H2O", "NTC", RefMat))

  # Titration, Dilution, Stock, NTC
meandf <- meandf %>% mutate(DilType = ifelse(str_detect(Sample, "in"), "Titration", "Dilution"),
                            # DilType = ifelse(str_detect(Sample, "100ng") || str_detect(Sample, "2e7"),
                            #                  "Stock", DilType),
                            DilType = ifelse(Sample == "H2O", "NTC", DilType))

  # Separate Sample into Amount (numerical) and SampleType (label)
meandf <- meandf %>% separate(Sample, into = c("Amount", "SampleType"),
                              sep = " ", extra = "merge")
meandf <- meandf %>% mutate(SampleType = ifelse(Amount == "H2O", "H2O", SampleType),
                           Amount = ifelse(Amount == "H2O", 0, Amount))

# Older data had % and OCI instead of "OCI in Molm"
meandf <- meandf %>% mutate(SampleType = ifelse(Amount == "1%", "OCI in Molm",
                                                SampleType),
                            Amount = ifelse(Amount == "1%", 1, Amount))

  # Theres an erroneous datapoint
meandf$Cq <- gsub(3.15, NA, meandf$Cq)

meandf$Cq[which(meandf$Cq == "NaN")] <- NA

meandf$Cq <- as.numeric(meandf$Cq)

meandf <- meandf %>% group_by(Fluor, SampleType, Date, XNA, Description, Amount,
                              Rep, RefMat, DilType) %>%
  summarise(Cq = round(mean(Cq, na.rm = T), digits = 2))

byFluor <- pivot_wider(meandf,
                    id_cols = c(SampleType, Amount, Date, Rep,
                                XNA, Description, RefMat, DilType),
                    names_from = Fluor,
                    values_from = Cq)


byFluor$HEX[which(is.null(byFluor$HEX))] <- NA



##########################################################
# END BASIC DATA CLEANING (FINALLY)
##########################################################


# Plot plasmid data
plasmids <- byFluor %>% filter(RefMat != "DNA") %>% ungroup(XNA) %>%
  select(-HEX) %>% mutate(XNA = as.numeric(str_extract(XNA, "[0-9.]*")))
plasmids$Amount <- as.numeric(plasmids$Amount)

# I'm a dingus.  All of these values are per uL, and I used 2
plasmids <- plasmids %>% mutate(Amount = 2*Amount)


avgs <- plasmids %>% group_by(Amount, SampleType) %>%
  dplyr::summarise(aF = mean(FAM), mF = median(FAM))
avgs <- melt(avgs, id = c("Amount", "SampleType"))
avgs$variable <- as.character(avgs$variable)
avgs$SampleType <- as.character(avgs$SampleType)

# Create trendline based on lowest average MUT plasmid value
fun.mutCqline <- function(x) -log2(x/(2*10^7)) + 
                     min(filter(avgs, variable == "aF" &
                                  SampleType == "MUT")$value, na.rm = T)
fun.wtCqline <- function(x) -log2(x/(2*10^7)) + 
                      min(filter(avgs, variable == "aF" &
                                  SampleType == "WT")$value, na.rm = T)


plasmids$FAM[is.na(plasmids$FAM)] <- 50

# Plot goals: One panel each of WT, HET, HET-in-WT
mutplasmids <- ggplot(data = filter(plasmids, SampleType == "MUT"),
                  aes(x = Amount, y = FAM, color = factor(SampleType))) +
  stat_summary(fun = "median", aes(color = "Median"), size = 0.75) +
  stat_summary(fun = "mean", aes(color = "Mean"), size = 0.75) +
  stat_summary(fun.data = mean_se, aes(color = "Std Dev"),
               geom = "errorbar", width = 0.2) +
  geom_point() +
  stat_function(fun = fun.mutCqline, aes(linetype = "Expected Ct"), color = "black") +
  scale_x_continuous(trans = reverselog_trans(10),
                     breaks = unique(plasmids$Amount),
                     labels = unique(plasmids$Amount)) +
  scale_linetype_manual(values = "dashed") +
  scale_color_manual(values = c("black", "darkgray", "red", "blue")) +
  ylim(c(min(filter(plasmids, SampleType == "MUT")$FAM), 50)) +
  labs(color = "Sample Type", y = "Ct", linetype = "",
       title = "Mutant plasmid dilution series", x = "Template Quantity (Copies)") +
  theme_bw() +
  guides(linetype = guide_legend(order = 1),
         color = guide_legend(order = 2))


wtplasmids <- ggplot(data = filter(plasmids, SampleType == "WT"),
                      aes(x = Amount, y = FAM, color = factor(SampleType))) +
  stat_summary(fun = "median", aes(color = "Median"), size = 0.75) +
  stat_summary(fun = "mean", aes(color = "Mean"), size = 0.75) +
  stat_summary(fun.data = mean_se, aes(color = "Std Dev"),
               geom = "errorbar", width = 0.2) +
  geom_point() +
  stat_function(fun = fun.wtCqline, aes(linetype = "Expected Ct"), color = "black") +
  scale_x_continuous(trans = reverselog_trans(10),
                     breaks = unique(plasmids$Amount),
                     labels = unique(plasmids$Amount)) +
  scale_color_manual(values = c("black", "darkgray", "red", "blue")) +
  scale_linetype_manual(values = "dashed") +
  ylim(c(min(filter(plasmids, SampleType == "MUT")$FAM), 50)) +
  labs(color = "Sample Type", y = "Ct", linetype = "",
       title = "Wild-Type plasmid dilution series", x = "Template Quantity (Copies)") +
  theme_bw() +
  guides(linetype = guide_legend(order = 1),
         color = guide_legend(order = 2))

# Make separate dataframes since we have different sample types on the same plot
titrdf <- plasmids %>% filter(SampleType == "MUT in WT" | Amount == 2e7)
titrdf <- titrdf[, c("SampleType", "Amount", "FAM", "XNA")]

titravg <- titrdf %>% group_by(Amount, SampleType, XNA) %>%
  dplyr::summarise(aF = mean(FAM), mF = median(FAM), sF = sd(FAM))
titrsd <- titravg %>% select(-mF)
titravg <- melt(titravg, id = c("Amount", "SampleType", "XNA"))


# Here's why your product doesn't work:
#   Different XNA concentrations don't change titration issue

xnaplasmidtitr <- ggplot() +
  geom_point(data = filter(titravg, variable != "sF"),   # Mean and median
             aes(x = Amount, y = value, color = factor(XNA)), size = 2) +
  geom_line(data = filter(titravg, variable != "sF" & Amount < 2e7),
             aes(x = Amount, y = value, color = factor(XNA))) +
  geom_hline(aes(yintercept = filter(titravg,                # Based on WT avg
                    variable == "aF" & (SampleType == "WT" & XNA == 0.5))$value,
                 linetype = "Expected Ct"), color = "chartreuse3", size = 1) +
  geom_hline(aes(yintercept = filter(titravg,                # Based on WT avg
                    variable == "aF" & (SampleType == "WT" & XNA == 1))$value,
                 linetype = "Expected Ct"), color = "blue", size = 1) +
  geom_hline(aes(yintercept = filter(titravg,                # Based on WT avg
                  variable == "aF" & (SampleType == "WT" & XNA == 2))$value,
                 linetype = "Expected Ct"), color = "purple", size = 1) +
  scale_x_continuous(trans = reverselog_trans(10),
                     breaks = unique(titravg$Amount),
                     labels = unique(titravg$Amount)) +
  scale_color_manual(values = c("red", "chartreuse3", "blue", "purple")) +
  scale_linetype_manual(values = "dashed") +
  ylim(c(min(filter(plasmids, SampleType == "MUT")$FAM), 50)) +
  labs(color = "XNA Conc. (uM)", y = "Ct", linetype = "",
       title = "Mutant plasmid titration into wild-type plasmid (2e7)",
       x = "MUT Template (Copies)") +
  theme_bw() +
  guides(linetype = guide_legend(order = 1),
         color = guide_legend(order = 2))

ggsave(paste0(basedir, "/Results PPT/", "mutPlasmids.jpg"), mutplasmids, width = 6, height = 5)
ggsave(paste0(basedir, "/Results PPT/", "wtPlasmids.jpg"), wtplasmids, width = 6, height = 5)
ggsave(paste0(basedir, "/Results PPT/", "titrPlasmids.jpg"), xnaplasmidtitr, width = 7, height = 5)

extrap <- titravg %>% filter(Amount == 2e7 &
                        (variable == "aF" & SampleType == "WT"))


ggplot(extrap, aes(x = XNA, y = value)) + geom_point() +
  xlim(c(0.5, 20)) + ylim(c(28, 50)) + geom_smooth()

##############################################
#  Plot cell line data
#############################################

# Next up: Cell lines.
#   Need plots of 0.5uM (dilution),
#       0.5uM (titration),
#       all XNA mixes
#   Find FAMdiff, normalize by 100ng OCI
#   Prove HEX works just fine to show it's an XNA thing

celldf <- byFluor %>% filter(RefMat == "DNA")
celldf$Amount <- gsub("100ng", 100, celldf$Amount)
celldf$Amount <- gsub("10ng", 10, celldf$Amount)
celldf$Amount <- gsub("1ng", 1, celldf$Amount)
celldf$Amount <- gsub("100pg", 0.1, celldf$Amount)
celldf$Amount <- gsub("10pg", 0.01, celldf$Amount)
celldf$Amount <- as.numeric(celldf$Amount)

celldf <- celldf %>% ungroup(Amount) %>% mutate(Amount = 2*Amount)

celldf$FAM[is.na(celldf$FAM)] <- 50
celldf$HEX[is.na(celldf$HEX)] <- 50

# Special cases
celldf[which(celldf$Date %in% c("20201229", "20210108") &
               celldf$SampleType %in% c("OCI", "Molm")), ]$HEX <- NA

celldf <- celldf %>% mutate(fluorDiff = abs(FAM - HEX))

cellnorm <- celldf %>% select(Date, SampleType, FAM, Amount, XNA)
# cellnorm$FAM[which(is.na(cellnorm$FAM))] <- 50
cellnormed <- cellnorm %>% group_by(Date, SampleType) %>%
  mutate(minFAM = min(FAM, na.rm = T)) %>%
  select(c(Date, SampleType, Amount, XNA, minFAM))

celldf <- plyr::join(celldf, cellnormed, match = "first")

celldf <- celldf %>% mutate(XNA = as.numeric(str_extract(XNA, "[0-9.]*")))


cellavgs <- celldf %>% group_by(Amount, SampleType, XNA) %>%
  dplyr::summarise(aF = mean(FAM, na.rm = T), mF = median(FAM), sF = sd(FAM),
                   aH = mean(HEX, na.rm = T), mH = median(HEX), sH = sd(HEX),
                   aDiff = mean(fluorDiff, na.rm = T),
                   sDiff = sd(fluorDiff, na.rm = T)) %>%
  mutate(XNA = as.numeric(str_extract(XNA, "[0-9.]*")))
cellavgs <- melt(cellavgs, id = c("Amount", "SampleType", "XNA"))
cellavgs$variable <- as.character(cellavgs$variable)
cellavgs$SampleType <- as.character(cellavgs$SampleType)


# Dilution df
celldildf <- celldf %>% filter(DilType != "Titration" &
                                  SampleType == "OCI")

# Needs to be 10^2 for cell lines
fun.hexCqline <- function(x) -log2(x/10^2) + 
  mean(celldildf[which(celldildf$Amount == 200), ]$HEX, na.rm = T)


# HEX plot (OCI dilution). > 2uM seems to inhibit control a bit
hexdilplot <- ggplot(data = filter(celldildf, SampleType == "OCI"),
       aes(x = Amount, y = HEX, color = factor(XNA))) + 
  geom_point() + stat_smooth(method = "lm") +
  stat_function(fun = fun.hexCqline,
                aes(linetype = "Expected Ct"), color = "black") +
  scale_x_continuous(trans = reverselog_trans(10)) +
  scale_linetype_manual(values = "dashed") +
  labs(color = "XNA (uM)",
       title = "Control amplicon; OCI dilution series",
       y = "Ct", x = "Template (ng)",
       linetype = "") + theme_bw() +
  ylim(c(min(celldildf$HEX), 50)) +
  guides(linetype = guide_legend(order = 1),
         color = guide_legend(order = 2))

# setwd(paste0(basedir, "Results PPT/"))
# ggsave("hexdilPlot.jpg", hexdilplot, width = 8, height = 5)

celldildf$Amount <- as.numeric(celldildf$Amount)

fun.famCqline <- function(x) -log2(x/10^2) + 
  mean(celldildf[which(celldildf$Amount == 200), ]$FAM, na.rm = T)
# FAM dilution plot
#  This one doesn't look great, it needs to be 0.5uM for titration
ggplot(data = celldildf, aes(x = Amount, y = FAM,
                             color = factor(XNA))) +
  geom_point() +
  geom_smooth(method = "lm") +
  scale_x_continuous(trans = reverselog_trans(10)) +
  stat_function(fun = fun.famCqline,
                aes(linetype = "Expected Ct"), color = "black")
  # stat_summary(fun = "median", color = "black") +
  # stat_summary(fun = "mean", color = "darkgray") +
  # stat_summary(fun.data = mean_se, geom = "errorbar", color = "red", width = 0.2)


# Titrations
celltitrdf <- celldf %>% filter(DilType != "Dilution" | Amount == 200) %>%
  mutate(XNA = as.numeric(str_extract(XNA, "[0-9.]*")))


cellsd <- cellavgs %>% filter(variable != "mF")

cellsd <- pivot_wider(cellsd,
                          id_cols = c(SampleType, Amount, XNA),
                          names_from = variable,
                          values_from = value) %>%
                          select(-aH, -mH, -sH, -aDiff, -sDiff)

hexcellsd <- pivot_wider(cellsd,
                         id_cols = c(SampleType, Amount, XNA),
                         names_from = variable,
                         values_from = value) %>%
                        select(-aF, -sF, -aDiff, -sDiff)

# Slide: OCI Dilution and Titration

cellsd$Amount <- as.numeric(cellsd$Amount)
cellavgs$Amount <- as.numeric(cellavgs$Amount)
celltitrdf$Amount <- as.numeric(celltitrdf$Amount)

fun.famtitr <- function(x) -log2(x/(2*10^2)) + 25

# fun.famtitrDiff <- function(x) -log2(x/(2*10^2))

# OCI titration vs. dilution graph

  # scale_shape_manual(values = c("HET", "HET in 2e4 WT"))

celldilsd <- cellsd %>% filter(SampleType %in% c("OCI", "Molm"))
celltitrsd <- cellsd %>% filter(Amount == 200 | SampleType == "OCI in Molm") %>%
  filter(XNA %in% c(0.5, 5, 20))
hextitrsd <- hexcellsd %>% filter(SampleType %in% c("OCI", "Molm"))

celldilavg <- cellavgs %>% filter(SampleType %in% c("OCI", "Molm"))
celltitravg <- cellavgs %>% filter(Amount == 200 | SampleType == "OCI in Molm") %>%
  filter(XNA %in% c(0.5, 5, 20))
hextitravg <- cellavgs %>% filter(SampleType %in% c("OCI", "Molm"))


ociXNADil <- ggplot() +
  geom_point(data = filter(celldilavg, variable == "aF"),  # Just dilution points
             aes(x = Amount, y = value,
                 shape = factor(SampleType),
                 color = factor(XNA), group = factor(XNA)), size = 2,
             position = position_dodge(width = 0.2)) +
  geom_line(data = filter(celldilavg,
                variable == "aF" & SampleType == "OCI"),   # Just dilution lines
            aes(x = Amount, y = value,
                color = factor(XNA), group = factor(XNA)),
            position = position_dodge(width = 0.2)) +
  scale_x_continuous(trans = reverselog_trans(10),
                     breaks = unique(cellavgs$Amount),
                     labels = unique(cellavgs$Amount)) +
  labs(color = "XNA Conc. (uM)", y = "Ct", linetype = "",
       title = "High XNA Concs; Dilution series",
       x = "Template Quantity (ng)",
       shape = "Sample Type") +
  scale_shape_manual(labels = c("WT DNA", "HET DNA"),
                     values = c(15:16)) +
  theme_bw() + 
  stat_function(fun = fun.famtitr,
                aes(linetype = "Expected Ct"), color = "black") +
  scale_linetype_manual(values = "dashed") +
  guides(linetype = guide_legend(order = 1),
         color = guide_legend(order = 2),
         shape = guide_legend(order = 3))

# setwd(paste0(basedir, "Results PPT/"))
# ggsave("ociXNADil.png", ociXNADil, width = 7, height = 5)


ociXNAtitr <- ggplot() +
  geom_point(data = filter(celltitravg, variable == "aF"),  # Just titration points
             aes(x = Amount, y = value,
                 shape = factor(SampleType),
                 color = factor(XNA), group = factor(XNA)), size = 2,
             position = position_dodge(width = 0.2)) +
  geom_line(data = filter(celltitravg,
                          variable == "aF" &
                            SampleType %in% c("OCI in Molm", "OCI")), # Just titration lines
            aes(x = Amount, y = value,
                color = factor(XNA), group = factor(XNA)),
            position = position_dodge(width = 0.2)) +
    geom_errorbar(data = filter(celltitrsd, SampleType %in% c("OCI in Molm", "OCI")),
                  aes(x = Amount, ymin = aF - sF, ymax = aF + sF,
                      color = factor(XNA)), width = 0.2,
                  position = position_dodge(width = 0.1)) +
  scale_x_continuous(trans = reverselog_trans(10),
                     breaks = unique(cellavgs$Amount),
                     labels = unique(cellavgs$Amount)) +
  labs(color = "XNA Conc. (uM)", y = "Ct", linetype = "",
       title = "High XNA Concs; Titration series",
       x = "Template Quantity (ng)",
       shape = "Sample Type") +
  scale_shape_manual(labels = c("WT DNA", "HET DNA", "HET in 200ng WT"),
                     values = c(15:17)) +
  theme_bw() + 
  stat_function(fun = fun.famtitr,
                aes(linetype = "Expected Ct"), color = "black") +
  scale_linetype_manual(values = "dashed") +
  guides(linetype = guide_legend(order = 1),
         color = guide_legend(order = 2),
         shape = guide_legend(order = 3))

setwd(paste0(basedir, "Results PPT/"))
ggsave("ociXNAtitr.png", ociXNAtitr, width = 6, height = 5)


# Create dummy legend
# leg <- ggplot(filter(celldf, SampleType != "Molm"),
#        aes(x = XNA, y = Amount, shape = factor(SampleType))) +
#   geom_point() +
#   labs(shape = "Sample Type") +
#   scale_shape_manual(labels = c("HET", "HET in 2e2 WT"),
#                      values = c(16, 17))

# For 0.5uM, n = 4 for OCI dilution, n = 8 for titration
celldf %>% filter(XNA %in% c(0.5, 5, 20) &
  SampleType %in% c("OCI in Molm", "OCI")) %>% group_by(XNA, SampleType, Amount) %>%
  summarise(n())

ggsave("legend.pdf", leg, width = 6, height = 6)

